Demo: Viewers: Routing (WIP)
- Cannot test the solution on older version of DG (public);
- The latest version has a problem during Demo package deployment: Operation caused an exception
NoSuchMethodError: The getter 'columns' was called on null.
Receiver: null
Tried calling: columns